name: CI Andresen CarService

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: 
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name : Step 1 - Checkout main branch from VSC 
      uses: actions/checkout@v3
      
    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Step 3 - Build with Maven
      run: mvn -B package --file CarService/pom.xml

    - name : Step 4 - Check target folder
      run : |
        cd CarService/target
        ls -a
    - name: Step 5 - Running tests
      run: mvn --batch-mode --update-snapshots verify -f CarService/pom.xml
    - name: Step 6 - Test coverage visualisation
      # You may pin to the exact commit or the version.
      # uses: PavanMudigonda/jacoco-reporter@ffe0b95c14292be4d076e56d50ba6c3b94c43a77
      uses: PavanMudigonda/jacoco-reporter@v4.8
      with:
        # Path to the JaCoCo coverage results file which will be used to generate a report. 
        #The only coverage results format supported is the JaCoCo XML schema.
        coverage_results_path: coverage.xml




      
